name: Angular CI/CD to VPS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Install dependencies
        run: npm ci

      - name: Lint and Test
        run: |
          npm run lint
          npm test -- --watch=false --browsers=ChromeHeadless

      - name: Build Angular App
        run: npm run build -- --prod

      - name: Setup SSH key
        uses: webfactory/ssh-agent@main
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            echo "Connected to VPS"
            
            # Define the folder where Angular app will live
            APP_PATH=/var/www/angular-app

            # Remove old files
            rm -rf $APP_PATH/*

            # Create folder if it doesn't exist
            mkdir -p $APP_PATH

            # Copy new build files
            cp -r /home/runner/work/${{ github.repository }}/dist/* $APP_PATH/

            echo "Angular app deployed successfully!"
